async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});let d={};try{d=await r.json()}catch{};if(!r.ok)throw Error(d.error||"Request failed");return d}
function formHandler(id,url,redirect){document.getElementById(id).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api(url,{method:"POST",body:JSON.stringify(Object.fromEntries(f))});location.href=redirect}catch(x){document.getElementById("msg").textContent=x.message}}}
async function logout(){await fetch("/api/logout",{method:"POST"});location.href="/"}
async function loadDashboard(){try{const me=await api("/api/me");if(me.role==="admin")location.href="/admin.html";document.getElementById("name").textContent="Welcome, "+me.name;document.getElementById("balance").textContent="KSh "+me.balance;const tasks=await api("/api/tasks");document.getElementById("tasks").innerHTML=tasks.map(t=>`<article class="card"><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><b>KSh ${t.reward}</b>${t.submission_id?`<p>Status: ${t.submission_status}</p>`:`<form onsubmit="submitTask(event,${t.id})"><textarea name="proof" placeholder="Paste your proof here" required></textarea><button class="btn">Submit proof</button></form>`}</article>`).join("");document.getElementById("wf").onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api("/api/withdraw",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});document.getElementById("wmsg").textContent="Request submitted.";e.target.reset()}catch(x){document.getElementById("wmsg").textContent=x.message}}}catch(e){location.href="/login.html"}}
async function submitTask(e,id){e.preventDefault();try{await api("/api/tasks/"+id+"/submit",{method:"POST",body:JSON.stringify({proof:new FormData(e.target).get("proof")})});loadDashboard()}catch(x){alert(x.message)}}
async function loadAdmin(){try{const me=await api("/api/me");if(me.role!=="admin")return location.href="/dashboard.html";const s=await api("/api/admin/overview");document.getElementById("stats").innerHTML=Object.entries(s).map(([k,v])=>`<div class="card"><small>${k}</small><h2>${v}</h2></div>`).join("");document.getElementById("tf").onsubmit=async e=>{e.preventDefault();try{await api("/api/admin/tasks",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});document.getElementById("tmsg").textContent="Task created.";e.target.reset();loadAdmin()}catch(x){document.getElementById("tmsg").textContent=x.message}};const subs=await api("/api/admin/submissions");document.getElementById("subs").innerHTML=subs.map(s=>`<div class="card row"><div><b>${esc(s.title)}</b> — ${esc(s.name)} — KSh ${s.reward}<br><small>${esc(s.proof)}</small><br>Status: ${s.status}</div>${s.status==="pending"?`<span><button onclick="review(${s.id},'approve')">Approve</button> <button onclick="review(${s.id},'reject')">Reject</button></span>`:""}</div>`).join("")||"<p>No submissions.</p>";const ws=await api("/api/admin/withdrawals");document.getElementById("withdrawals").innerHTML=ws.map(w=>`<div class="card row"><div>${esc(w.name)} — ${esc(w.phone)} — KSh ${w.amount}<br>Status: ${w.status}</div>${w.status==="pending"?`<span><button onclick="withdrawReview(${w.id},'paid')">Mark paid</button> <button onclick="withdrawReview(${w.id},'rejected')">Reject</button></span>`:""}</div>`).join("")||"<p>No withdrawals.</p>"}catch(e){location.href="/login.html"}}
async function review(id,action){await api("/api/admin/submissions/"+id,{method:"POST",body:JSON.stringify({action})});loadAdmin()}
async function withdrawReview(id,action){await api("/api/admin/withdrawals/"+id,{method:"POST",body:JSON.stringify({action})});loadAdmin()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
